from bge import events
from bge.logic import keyboard

KEYS = {
    # alphabet
    "A" : keyboard.inputs[ events.AKEY ],
    "B" : keyboard.inputs[ events.BKEY ],
    "C" : keyboard.inputs[ events.CKEY ],
    "D" : keyboard.inputs[ events.DKEY ],
    "E" : keyboard.inputs[ events.EKEY ],
    "F" : keyboard.inputs[ events.FKEY ],
    "G" : keyboard.inputs[ events.GKEY ],
    "H" : keyboard.inputs[ events.HKEY ],
    "I" : keyboard.inputs[ events.IKEY ],
    "J" : keyboard.inputs[ events.JKEY ],
    "K" : keyboard.inputs[ events.KKEY ],
    "L" : keyboard.inputs[ events.LKEY ],
    "M" : keyboard.inputs[ events.MKEY ],
    "N" : keyboard.inputs[ events.NKEY ],
    "O" : keyboard.inputs[ events.OKEY ],
    "P" : keyboard.inputs[ events.PKEY ],
    "Q" : keyboard.inputs[ events.QKEY ],
    "R" : keyboard.inputs[ events.RKEY ],
    "S" : keyboard.inputs[ events.SKEY ],
    "T" : keyboard.inputs[ events.TKEY ],
    "U" : keyboard.inputs[ events.UKEY ],
    "V" : keyboard.inputs[ events.VKEY ],
    "W" : keyboard.inputs[ events.WKEY ],
    "X" : keyboard.inputs[ events.XKEY ],
    "Y" : keyboard.inputs[ events.YKEY ],
    "Z" : keyboard.inputs[ events.ZKEY ],
    
    # alphanumeric numbers
    "alpha0" : keyboard.inputs[ events.ZEROKEY  ],
    "alpha1" : keyboard.inputs[ events.ONEKEY   ],
    "alpha2" : keyboard.inputs[ events.TWOKEY   ],
    "alpha3" : keyboard.inputs[ events.THREEKEY ],
    "alpha4" : keyboard.inputs[ events.FOURKEY  ],
    "alpha5" : keyboard.inputs[ events.FIVEKEY  ],
    "alpha6" : keyboard.inputs[ events.SIXKEY   ],
    "alpha7" : keyboard.inputs[ events.SEVENKEY ],
    "alpha8" : keyboard.inputs[ events.EIGHTKEY ],
    "alpha9" : keyboard.inputs[ events.NINEKEY  ],
    
    # modifiers keys
    "CapsLock"     : keyboard.inputs[ events.CAPSLOCKKEY   ],
    "RightControl" : keyboard.inputs[ events.RIGHTCTRLKEY  ],
    "LeftControl"  : keyboard.inputs[ events.LEFTCTRLKEY   ],
    "LeftAlt"      : keyboard.inputs[ events.LEFTALTKEY    ],
    "RightAlt"     : keyboard.inputs[ events.RIGHTALTKEY   ],
    "RightShift"   : keyboard.inputs[ events.RIGHTSHIFTKEY ],
    "LeftShift"    : keyboard.inputs[ events.LEFTSHIFTKEY  ],
    
    # arrow keys
    "UpArrow"    : keyboard.inputs[ events.UPARROWKEY    ],
    "DownArrow"  : keyboard.inputs[ events.DOWNARROWKEY  ],
    "LeftArrow"  : keyboard.inputs[ events.LEFTARROWKEY  ],
    "RightArrow" : keyboard.inputs[ events.RIGHTARROWKEY ],
    
    # numpad keys
    "Pad0"        : keyboard.inputs[ events.PAD0        ],
    "Pad1"        : keyboard.inputs[ events.PAD1        ],
    "Pad2"        : keyboard.inputs[ events.PAD2        ],
    "Pad3"        : keyboard.inputs[ events.PAD3        ],
    "Pad4"        : keyboard.inputs[ events.PAD4        ],
    "Pad5"        : keyboard.inputs[ events.PAD5        ],
    "Pad6"        : keyboard.inputs[ events.PAD6        ],
    "Pad7"        : keyboard.inputs[ events.PAD7        ],
    "Pad8"        : keyboard.inputs[ events.PAD8        ],
    "Pad9"        : keyboard.inputs[ events.PAD9        ],
    "PadPeriod"   : keyboard.inputs[ events.PADPERIOD   ],
    "PadSlash"    : keyboard.inputs[ events.PADSLASHKEY ],
    "PadAsterisk" : keyboard.inputs[ events.PADASTERKEY ],
    "PadMinus"    : keyboard.inputs[ events.PADMINUS    ],
    "PadEnter"    : keyboard.inputs[ events.PADENTER    ],
    "PadPlus"     : keyboard.inputs[ events.PADPLUSKEY  ],
    
    # function keys
    "F1"  : keyboard.inputs[ events.F1KEY  ],
    "F2"  : keyboard.inputs[ events.F2KEY  ],
    "F3"  : keyboard.inputs[ events.F3KEY  ],
    "F4"  : keyboard.inputs[ events.F4KEY  ],
    "F5"  : keyboard.inputs[ events.F5KEY  ],
    "F6"  : keyboard.inputs[ events.F6KEY  ],
    "F7"  : keyboard.inputs[ events.F7KEY  ],
    "F8"  : keyboard.inputs[ events.F8KEY  ],
    "F9"  : keyboard.inputs[ events.F9KEY  ],
    "F10" : keyboard.inputs[ events.F10KEY ],
    "F11" : keyboard.inputs[ events.F11KEY ],
    "F12" : keyboard.inputs[ events.F12KEY ],
    "F13" : keyboard.inputs[ events.F13KEY ],
    "F14" : keyboard.inputs[ events.F14KEY ],
    "F15" : keyboard.inputs[ events.F15KEY ],
    "F16" : keyboard.inputs[ events.F16KEY ],
    "F17" : keyboard.inputs[ events.F17KEY ],
    "F18" : keyboard.inputs[ events.F18KEY ],
    "F19" : keyboard.inputs[ events.F19KEY ],
    
    # other keys
    "AccentGrave"  : keyboard.inputs[ events.ACCENTGRAVEKEY  ],
    "BackSlash"    : keyboard.inputs[ events.BACKSLASHKEY    ],
    "BackSpace"    : keyboard.inputs[ events.BACKSPACEKEY    ],
    "Comma"        : keyboard.inputs[ events.COMMAKEY        ],
    "Delete"       : keyboard.inputs[ events.DELKEY          ],
    "End"          : keyboard.inputs[ events.ENDKEY          ],
    "Equal"        : keyboard.inputs[ events.EQUALKEY        ],
    "Esc"          : keyboard.inputs[ events.ESCKEY          ],
    "Home"         : keyboard.inputs[ events.HOMEKEY         ],
    "Insert"       : keyboard.inputs[ events.INSERTKEY       ],
    "LeftBracket"  : keyboard.inputs[ events.LEFTBRACKETKEY  ],
    "LineFeed"     : keyboard.inputs[ events.LINEFEEDKEY     ],
    "Minus"        : keyboard.inputs[ events.MINUSKEY        ],
    "PageDown"     : keyboard.inputs[ events.PAGEDOWNKEY     ],
    "PageUp"       : keyboard.inputs[ events.PAGEUPKEY       ],
    "PauseBreak"   : keyboard.inputs[ events.PAUSEKEY        ],
    "Period"       : keyboard.inputs[ events.PERIODKEY       ],
    "Quote"        : keyboard.inputs[ events.QUOTEKEY        ],
    "RightBracket" : keyboard.inputs[ events.RIGHTBRACKETKEY ],
    "Enter"        : keyboard.inputs[ events.ENTERKEY        ],
    "SemiColon"    : keyboard.inputs[ events.SEMICOLONKEY    ],
    "Slash"        : keyboard.inputs[ events.SLASHKEY        ],
    "Space"        : keyboard.inputs[ events.SPACEKEY        ],
    "Tab"          : keyboard.inputs[ events.TABKEY          ],
}
